//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toernooi
{
    using System;
    using System.Collections.Generic;
    
    public partial class InscripcionEquipos
    {
        public int idInscripcionEquipo { get; set; }
        public System.DateTime fechaInscripcion { get; set; }
        public int Equipos_idEquipo { get; set; }
        public int Torneos_idTorneo { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Torneos Torneos { get; set; }
    }
}
