//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toernooi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jugadores()
        {
            this.DetallePartido = new HashSet<DetallePartido>();
        }
    
        public int idJugador { get; set; }
        public string documento { get; set; }
        public string nomJugador { get; set; }
        public string apeJugador { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public Nullable<int> dorsal { get; set; }
        public int Equipos_idEquipo { get; set; }
        public int PosicionesJug_idPosicionJug { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePartido> DetallePartido { get; set; }
        public virtual Equipos Equipos { get; set; }
        public virtual PosicionesJug PosicionesJug { get; set; }
    }
}
