//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toernooi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partidos()
        {
            this.DetallePartido = new HashSet<DetallePartido>();
        }
    
        public int idPartido { get; set; }
        public string EquipoLocal { get; set; }
        public string EquipoVisitante { get; set; }
        public string Cancha { get; set; }
        public System.DateTime fechaPartido { get; set; }
        public Nullable<int> golesLocal { get; set; }
        public Nullable<int> golesVisitante { get; set; }
        public string nomArbitro { get; set; }
        public string evento { get; set; }
        public int Torneos_idTorneo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePartido> DetallePartido { get; set; }
        public virtual Torneos Torneos { get; set; }
    }
}
