//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toernooi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntosPorEquipo
    {
        public int idPuntosPorEquipo { get; set; }
        public int Torneos_idTorneo { get; set; }
        public int Equipos_idEquipo { get; set; }
        public int PJ { get; set; }
        public int PG { get; set; }
        public int PP { get; set; }
        public int PE { get; set; }
        public int GF { get; set; }
        public int GC { get; set; }
        public int DG { get; set; }
        public int PTS { get; set; }
        public string grupo { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Torneos Torneos { get; set; }
    }
}
