//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toernooi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Torneos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Torneos()
        {
            this.InscripcionEquipos = new HashSet<InscripcionEquipos>();
            this.Partidos = new HashSet<Partidos>();
            this.PuntosPorEquipo = new HashSet<PuntosPorEquipo>();
        }
    
        public int idTorneo { get; set; }
        public int cantEquipos { get; set; }
        public string nomResponsable { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public string nomTorneo { get; set; }
        public int Usuarios_idUsuario { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public string docResponsable { get; set; }
        public int tipoEnteOrganizador_idTipoEnte { get; set; }
        public int tiposTorneos_idTipoTorneo { get; set; }
        public bool idaYvuelta { get; set; }
        public string nomEnteOrgan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InscripcionEquipos> InscripcionEquipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partidos> Partidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PuntosPorEquipo> PuntosPorEquipo { get; set; }
        public virtual tipoEnteOrganizador tipoEnteOrganizador { get; set; }
        public virtual TiposTorneo TiposTorneo { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
